[workspace]
resolver = "3"
members = [
  "backend"
]
default-members = [
  "backend"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
authors = [
  "Invra <identificationsucks@gmail.com>",
  "UltimatePlayer97 <gogole.help134@gmail.com>",
  "RealMeddsam <meddsamreal@gmail.com>"
]

[workspace.dependencies]
objc2 = "0.6"
block2 = "0.6"
objc2-foundation = "0.3"
objc2-user-notifications = "0.3"
