[package]
name = "rbackend"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_os = "linux")'.dependencies]
zbus.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
block2.workspace = true
objc2-foundation.workspace = true
objc2-user-notifications.workspace = true
